server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xyzkuanghuan/springcloud
          search-paths: config-repo
          username: 
          password: 